[[steps]]
name = "Setup Rust"
command = ["fluentci run --wasm rust setup"]

[[steps]]
name = "Run tests"
command = [
  "fluentci run --wasm postgres start",
  "curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash",
  "cargo-binstall sqlx-cli -y",
  "sqlx migrate run",
  "cargo sqlx prepare",
  "cargo test",
]
env = [
  "POSTGRES_USER=postgres",
  "POSTGRES_DB=demo",
  "DATABASE_URL=postgres://postgres@localhost/demo",
]

[[steps]]
name = "Run build"
command = ["fluentci run --wasm rust build"]
env = ["DATABASE_URL=postgres://postgres@localhost/demo"]
